### ISSUE TITLE
Design of Passive Magnetic Stabilization

### ISSUE THREAD

**Issue by tpreynolds** [tpreynolds/uw_hs1_adcs#8]
- Size and choose orientation of a permanent magnet so that the s/c will be nadir pointing when over UW. 
- Size hysteresis rods to provide sufficient damping so that the settling time is on the order of days (sorry, we don't have a concrete requirement here yet...this is a WAG)
- Add the magnet/rod characteristics to the sim as an optional mode.

**Comment by tpreynolds** [comment]
Will add Bijan to this when he accepts the invite.

**Comment by scrice** [comment]
We have a functional simulation with a set of parameters. If this is the direction we choose to go, it will be available and we can simulate different parameters for the magnets.
